blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^posts/', include('posts.urls', namespace="posts")),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

posts/urls.py
from django.conf.urls import url
from posts import views

urlpatterns = [
    url(r'^create/$', views.post_create, name="create"),
    url(r'^list/$', views.post_list, name="list"),
	url(r'^detail/(?P<post_slug>[-\w]+)/$', views.post_detail, name="detail"),
	url(r'^update/(?P<post_slug>[-\w]+)/$', views.post_update, name="update"),
	url(r'^delete/(?P<post_slug>[-\w]+)/$', views.post_delete, name="delete"),
]

posts/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, default=1)
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    image = models.ImageField(null=True, blank=True, upload_to="post_images")
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"post_slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]


def create_slug(instance, new_slug=None):
    slug = slugify (instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s"%(slug,qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug=create_slug(instance)

pre_save.connect(pre_save_post_reciever,sender=Post)

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content','image', 'draft', 'publish']

        widgets={
        'publish': forms.DateInput(attrs={"type":"date"}),
        }

posts/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post
from django.shortcuts import get_object_or_404
from .forms import PostForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib.parse import quote
from django.conf import settings
from django.utils import timezone
from django.db.models import Q

def post_home(request):
    return HttpResponse("<h1> Hello</h1>")
    
# def post_create(request):
#     return HttpResponse("<h1> Create </h1>")
def post_create(request):
    if not (request.user.is_staff or request.user.is_superuser):
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit = False)
        post.author = request.user
        post.save()
        messages.success(request, "Successfully Created!")
        return redirect("posts:list")
    context = {
    "title": "Create",
    "form": form,
    }
    return render(request, 'post_create.html', context)

# def post_detail(request):
#     return HttpResponse("<h1> Detail </h1>")
def post_detail(request, post_slug):
    instance = get_object_or_404(Post, slug=post_slug)
    if instance.publish>timezone.now().date() or instance .draft:
        if not (request.user.is_staff or request.user.is_superuser):
            raise Http404
    context = {
    "title": "Detail",
    "instance": instance,
    "share_string": quote(instance.content)
    }
    return render(request, 'post_detail.html', context)

def post_update(request, post_slug):
    if not (request.user.is_staff or request.user.is_superuser):
        raise Http404
    instance = get_object_or_404(Post, slug=post_slug)
    form = PostForm(request.POST or None, request.FILES or None, instance = instance)
    if form.is_valid():
        form.save()
        messages.success(request, "Successfully Edited!")
        return redirect(instance.get_absolute_url())
    context = {
    "form":form,
    "instance": instance,
    "title": "Update",
    }
    return render(request, 'post_update.html', context)

def post_delete(request, post_slug):
    if not (request.user.is_staff or request.user.is_superuser):
        raise Http404
    instance = get_object_or_404(Post, slug=post_slug)
    instance.delete()
    messages.success(request, "Successfully Deleted!")
    return redirect("posts:list")

# def post_list(request):
#     return HttpResponse("<h1> List </h1>")
def post_list(request):
    today = timezone.now().date()
    object_list = Post.objects.filter(draft=False).filter(publish__lte=today)
    if request.user.is_staff or request.user.is_superuser:
        object_list = Post.objects.all()

    # query = request.GET.get("q")
    # if query:
    #     object_list = object_list.filter(title__icontains=query)

    query = request.GET.get("q")
    if query:
        object_list = object_list.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(author__first_name__icontains=query)|
            Q(author__last_name__icontains=query)
            ).distinct()

    paginator = Paginator(object_list, 5)
    page = request.GET.get('page')
    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)

    context = {
    "object_list": objects,
    "title": "List",
    "user": request.user,
    "today": today
    }
    return render(request, 'post_list.html', context)


     

posts/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    {% block title %}

    {% endblock title %}
    </title>

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    {% include "messages.html" %}

    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
</script>
</body>
</html>

posts/templates/messages.html
{% if messages %}
<ul class='messages'>
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
    {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

posts/templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">DarthHamza</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Some Page</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Staff Only <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

posts/templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Create
{% endblock title %}


{% block content %}
    <h1>The Post {{title}} Page</h1>
    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
         {{form|crispy}}
        <input type="submit" value="Create Post">
    </form>
{% endblock content %}

posts/templates/post_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post Delete</title>
</head>
<body>
    <h1>The Post Delete Page</h1>
</body>
</html>

posts/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}

{% block title %}
{{title}}
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
		{% if instance.image %}
		    <img src="{{instance.image.url}}" alt="" class="img-responsive">
		{% endif %}
		<h1>{{instance.title}} <small>{{instance.publish}}</small></h1>
		{{instance.content| linebreaks}} <br>

		Author: {{instance.author.get_full_name}} <br>

        <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
            Share on Facebook
        </a><br>

        <a href="https://twitter.com/home?status={{instance.content|truncatechars:35|urlify}}%20{{request.build_absolute_uri}}">
            Share on Twitter
        </a><br>

        <a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{instance.title|urlify}}&summary={{instance.content|truncatechars:35|urlify}}&source={{request.build_absolute_uri}}">
        Share on Linkedin
        </a>
    </div>
</div>
{% endblock content %}

posts/templates/post_list.html
{% extends "base.html" %}

{% block title %}
{{title}}
{% endblock title %}

{% block content %}
    <h1>{{title}}</h1>
<div class="row">
<form action="" method="GET">
    <input type="text" name='q' placeholder="Search posts" value="{{request.GET.q}}">
    <input type="submit" value="Search">
</form>

{% for object in object_list %}
    <div class="col-sm-6 col-sm-offset-3">
        <div class="thumbnail">
            {% if object.image %}
                <img src="{{object.image.url}}" alt="" class="img-responsive">
            {% endif %}
            <div class="caption">
                <h3><a href="{{ object.get_absolute_url }}">{{object.title}}</a><small> {{object.publish|timesince }} ago</small></h3>

                {% if object.draft %}<h3>Draft</h3>{% endif %}
                {% if object.publish > today %}<h3>Future Post</h3>{% endif %}

                <p>{{object.content|linebreaks|truncatechars:100}}</p>
                <p><a href="{{ object.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
            </div>
        </div>
    </div>
{% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page={{ object_list.previous_page_number }}&q={{ request.GET.q }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}&q={{ request.GET.q }}">next</a>
        {% endif %}
    </span>
</div>
    
{% endblock content %}

posts/templates/post_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Post Update
{% endblock title %}


{% block content %}
  <h1>The Post {{title}} Page</h1>
<form action="{% url 'posts:update' post_slug=instance.slug %}" method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form|crispy}}
<input type="submit" value="Update Post">
</form>
{% endblock content %}